### ISSUE TITLE
US 01.05.01 Real time attendance and milestones

### ISSUE THREAD

**Issue by dpardell** [CMPUT301W24T18/EventLinkQR#16]
# US 01.05.01

## Description

As an organizer, I want to track real-time attendance and receive alerts for important milestones.

## Requirements

- The system should support real-time (no manual refresh) updates for attendance.
- The system should support specified milestones pertaining to event stats.
- The system should support notifications triggered by the system (rather than a user).

## Tasks
- #17 
- #18 
- #19 

## Acceptance Criteria
- [ ] The system should update attendance on the organizers interface without any user interaction.
- [ ] The system should update attendance within 5 seconds (under normal network conditions).
- [ ] The system should allow users to specify milestones.
- [ ] The system notifies the organizer when a milestone is achieved.

## Notes

Any useful notes here.
