### ISSUE TITLE
US 01.08.01 User check-in map

### ISSUE THREAD

**Issue by dpardell** [CMPUT301W24T18/EventLinkQR#25]
# US 01.08.01

## Description
As an organizer, I want to see on a map where users are checking in from.  

## Requirements

- The system should support collecting geolocation data.
- The system should allow attendees to opt out of sharing geolocation data.
- The system should provide a map UI for viewing attendee check in locations.

## Tasks
- #26 
- #27 

## Acceptance Criteria
- [x] There is a map UI visible by organizers.
- [x] Check locations are visible on the map.
- [x] An organizer cannot see the check-in location from attendees who have opted out.

## Notes

Any useful notes here.

**Comment by dpardell** [comment]
We need to make map update in real-time for part 4
