### ISSUE TITLE
US 01.01.01 Generate Unique QR Code

### ISSUE THREAD

**Issue by dpardell** [CMPUT301W24T18/EventLinkQR#3]
# US 01.01.01

## Description

As an organizer, I want to create a new event and generate a unique QR code for attendee check-ins.

## Tasks
- #1 
- #4 

## Acceptance Criteria
- [x] Upon opening the app, a user can create an event.
- [x] The system generates and displays a QR code after the user creates an event.
- [x] The system generates unique QR codes for X events.

## Notes
