### ISSUE TITLE
US 02.02.03 Update User Profile

### ISSUE THREAD

**Issue by Q-Basia** [CMPUT301W24T18/EventLinkQR#38]
# US 02.02.03

## Description
As an attendee, I want to update information such as name, homepage, and contact information on my profile.

## Requirements

- The system should only requires a username.
- The system should support updating profile info.
- The system should display up to date profile information.

## Tasks
- #37 

## Acceptance Criteria

- [x] When an account is created, just a username is required.
- [x] Attendees are able to view and updated their profile.
- [x] When a profile is updated, the view shows accurate and up to date information.
