### ISSUE TITLE
US 02.03.01 Receiving Push Notification

### ISSUE THREAD

**Issue by Q-Basia** [CMPUT301W24T18/EventLinkQR#39]
# US 02.03.01

## Description
As an attendee, I want to receive push notifications with important updates from the event organizers

## Requirements

- The system should support push notifications
- The system should create push notifications when an organizer sends an update.
- The system should have an interface for the user to view all of their notifications.
- The system should have a way of denoting updates as read or unread for the user.

## Tasks
- #40
- #41

## Acceptance Criteria

- [x] Attendees receive push notifications from organizers for events their are attending.
- [x] When viewing a notification, the attendee can see which event it pertains to.
- [x] When attendees read a message from an organizer, it is no longer marked as new / unread.

## Notes
android support push notifications:  https://developer.android.com/develop/ui/views/notifications

**Comment by dpardell** [comment]
There is still some work to do in the view for attendees to see messages
