### ISSUE TITLE
US 01.11.01 Optionally limit number of attendees

### ISSUE THREAD

**Issue by dpardell** [CMPUT301W24T18/EventLinkQR#69]
# US 01.11.01

## Description

As an organizer, I want to OPTIONALLY limit the number of attendees that can sign up for an event.

## Requirements

- The system should provide organizers with the option to limit the number of attendees that can sign up for an event.

## Tasks

- #70 
- #73 

## Acceptance Criteria

- [ ] When creating an event, the organizer can set a limit on the number of attendees.
- [ ] When editing an event, the organizer can set a limit on the number of attendees?
- [ ] If a limit is not provided, attendees can still sign up and there is no limit.
