### ISSUE TITLE
US 02.08.01 Browse event posters/details

### ISSUE THREAD

**Issue by dpardell** [CMPUT301W24T18/EventLinkQR#74]
# NUS 02.08.01

## Description
As an attendee, I want to browse event posters/event details of other events.

## Requirements
- The system provides a view listing all available events that have been created by an organizer.

## Tasks
- #75 

## Acceptance Criteria
- [x] Attendee can view a listing of available events.
- [x] Upon viewing an event, attendee can see its poster and event details.
- [x] If user has also organized events, they do not appear in the list.
