### ISSUE TITLE
US 01.03.01 Send notifications to attendees

### ISSUE THREAD

**Issue by dpardell** [CMPUT301W24T18/EventLinkQR#9]
# US 01.03.01

## Description

As an organizer, I want to send notifications to all attendees through the app.

## Requirements

- The system should allow organizers to send notifications.
- The system should allow attendees to view a list of notifications they have received.
- The system should display the name of the event that a message is for.
- The system should notify an attendee when they receive a notification.

## Tasks
- #10 
- #11 
- #12 

## Acceptance Criteria
- [x] An organizer can compose a message to all attendees of a given event.
- [x] The name of the event that the message is for is visible when composing a message.
- [x] An organizer can view previously sent messages.

## Notes

Any useful notes here.

**Comment by dpardell** [comment]
There are still a few things to tackle in Part 4 here, mainly being able to view the notifications that you have sent as an organizer.
